### ISSUE TITLE
L.control.layers refresh layer state

### ISSUE THREAD

**Issue by ejovrh2** [ptma/Leaflet.Legend#1]
Hi,

cool plug in.
If I had L.control.layers in map it would be cool also to turn off/on layer in both direction (legend and control layers).
Where are controls for turn on/off layer.
Is it possible to put legend in toolbar button to show and hide on click.

Thanks in advance

**Comment by ptma** [comment]
Are you expecting an option like `collapsed`?
Set `collapsed: true`,  the legend control panel will be collapsed.
