### ISSUE TITLE
circle symbols

### ISSUE THREAD

**Issue by IkLaa** [ptma/Leaflet.Legend#2]
hello!
i found this code very helpful, i just have one issue: i try to make the circle symbols bigger increasing the radius but i think the maximum is about 10px.
how can i make it work ?

**Comment by ptma** [comment]
Hi！
The maximum radius depends on the width and height of the symbol, You should increase `symbolWidth` and `symbolHeight`.
Reference code: [src/leaflet.legend.js#L81](https://github.com/ptma/Leaflet.Legend/blob/master/src/leaflet.legend.js#L81)
